// <auto-generated />
using System;
using SYNCV.API.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SYNCV.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190618150217_InitialCreateV3")]
    partial class InitialCreateV3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("SYNCV.API.Models.AuthLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Details");

                    b.Property<DateTime>("LogDate");

                    b.Property<int>("LogStatusId");

                    b.Property<int>("LogTypeId");

                    b.Property<string>("UsedUser");

                    b.Property<string>("UserIP");

                    b.HasKey("Id");

                    b.HasIndex("LogStatusId");

                    b.HasIndex("LogTypeId");

                    b.ToTable("AuthLogs");
                });

            modelBuilder.Entity("SYNCV.API.Models.LogStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("LogStatus");
                });

            modelBuilder.Entity("SYNCV.API.Models.LogType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("LogTypes");
                });

            modelBuilder.Entity("SYNCV.API.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("SYNCV.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("blob");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("blob");

                    b.Property<int>("PersonId");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SYNCV.API.Models.AuthLog", b =>
                {
                    b.HasOne("SYNCV.API.Models.LogStatus", "LogStatus")
                        .WithMany()
                        .HasForeignKey("LogStatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SYNCV.API.Models.LogType", "LogType")
                        .WithMany()
                        .HasForeignKey("LogTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SYNCV.API.Models.User", b =>
                {
                    b.HasOne("SYNCV.API.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
